### ISSUE TITLE
Clarify presentation of Lenstra's algorithm

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#14]
Page 11, paragraph 3: The presentation of Lenstra algorithm is
confusing. Going backward with (Lenstra actually goes...) even more so.
This paragraph should be rewritten to summarize properly Lenstra algorithm.
Lenstra algorithm cannot pick a non r-th power residue in 
deterministic polynomial time.

**Comment by javad-doliskani** [comment]
I dropped the sentence:
"...and solutions to Hilbert's theorem 90"

Add it if you like.

**Comment by defeo** [comment]
@javad-doliskani, I just made some minor edits to your text, where I found it was confusing. Accept the PR if you like it.
