### ISSUE TITLE
Present divide and conquer strategy more abstractly

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#15]
Page 14, line -2 and Page 17 line -11.
Generally it is better to write double-and-add schemes as an associative
operation in a monoid and let the implementor choses the addition chain
to use. In this case give the law '*' on tuples
T_j=(zeta^{-j},sigma^j,xi_j,theta_j) such that
T_{j}*T_{k} = T_{j+k}

**Comment by defeo** [comment]
Seriously?! This request is absurd!

**Comment by schost** [comment]
Actually, I kind of agree.. If I understand correctly what s/he's saying, we already have something like that p. 5, and I like that there's only one formula.

**Comment by defeo** [comment]
@schost, would you mind handling this one?

**Comment by schost** [comment]
Done (w/o monoids). Hopefully the formulas aren't too wrong. I tried to harmonize the notation a tiny bit.

**Comment by defeo** [comment]
At the beginning of p15, there is

> so that we want to compute θ_a,r = θ_a

and, shortly thereafter,

> Then θ_a = θ_a,r

Isn't this weird?

**Comment by defeo** [comment]
In the proof of Prop. 8, a letter *b* is used for a generic polynomial. However in the whole section *b* is something else (a divisor of h). Maybe we should pick a different letter?

**Comment by defeo** [comment]
I double checked. I believe formulas are correct. Thx!

**Comment by schost** [comment]
That's weird; I'll fix that tonight.
