### ISSUE TITLE
Give details on the conjecture

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#17]
Page 24, line 2: some detail on of far the conjecture has been checked
would be welcome.

**Comment by defeo** [comment]
@jpflori, can you double check that what I've written at the end of 5.1 is correct?

Could you also add a short readme to https://github.com/defeo/ffisom/blob/master/misc/conjdata/ explaining what's in there?

Then, I think this issue can be closed.

**Comment by jpflori** [comment]
The first part has been done in bd9e9d7eb

The second one should be addressed by 79860e 42e6ad and 701345.

**Comment by defeo** [comment]
So, can we close this?

**Comment by jpflori** [comment]
If you are happy with what i did, sure.
