### ISSUE TITLE
Rename Section 3.1

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#2]
Suggestion: rename **"Fast Kummer-type algorithm for p|r"** → **"Allombert's algorithm"**.

Please vote (by commenting, or by clicking on the smiley).

**Comment by jpflori** [comment]
I liked the Kummer/Artin-Schreier balance. So maybe we could just simplify 3.1 and 3.2 to the Kummer case and the Artin-Schreier case.

**Comment by jpflori** [comment]
Closed by d1701c0eed9f4
