### ISSUE TITLE
Plots are slow to render

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#21]
The graphic are slow to be displayed by the PDF reader and the referee
printer could not print the pages which include graphics.  Maybe the
graphic could be produced at a lower resolution.

**Comment by defeo** [comment]
I don't think this is any business of the reviewer's

**Comment by javad-doliskani** [comment]
True, but it is also a bit annoying that I have to wait a few seconds to scroll through those pages on my 16-core machine.

**Comment by defeo** [comment]
See https://github.com/matplotlib/matplotlib/issues/5967/
