### ISSUE TITLE
MM or ^ω?

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#6]
The intro uses O(n^ω) for linear algebra. Section 3.1.2 uses MM(n). We should make a decision.

**Comment by jpflori** [comment]
As we use \omega for modcomp (because of linalg) I say we use it for linalg as well...

**Comment by defeo** [comment]
I had the same advice, but was wating for Éric's cleanup, in case he decided to change the ω

**Comment by defeo** [comment]
This has been adressed by Éric. There is no more MM
