### ISSUE TITLE
We should say somewhere that (some) runtimes are Las Vegas

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#7]
Reported by @schost

**Comment by defeo** [comment]
Note we say in the first paragraph of Sec. 2:

> Most of the algorithms we present are randomized; we use the *big-Oh* notation O() to express average asymptotic complexity, and we will make it clear when this complexity depends on heuristics.

**Comment by schost** [comment]
Sorry, I missed it. I've added a lot of "expected" here and there, I'll have to remove them.

**Comment by defeo** [comment]
Being redundant is not necessarily bad. I wouldn't care leaving the "expected".
